spring:
  application:
    name: cairtech
  expiration: 86400000
  secretKey: "secret"
  admin:
    email: ${admin-email:admin@cairtech.com}
    password: ${admin-password:admin123}
    phoneNumber: ${admin-phoneNumber:0000000000}

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/cairtech
    username: postgres
    password: adminuser

logging:
  level:
    com.fasterxml.jackson: DEBUG
    org.springframework.data: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE
